image: microsoft/dotnet:sdk

pipelines:
  default:
    - step: &build
        name: Build
        caches:
          - dotnetcore
        script:
          - chmod +x ./build.sh
          - sh ./build.sh
    - step: &unittest
        name: Unit tests
        script:
          - chmod +x ./run-unittests.sh
          - sh ./run-unittests.sh
    - step: &builddockercontainer
        name: Build Docker Container and run integrationtests
        script:
          - chmod +x ./publish-and-dockerize.sh
          - sh ./publish-and-dockerize.sh
          - chmod +x ./run-integrationtests.sh
          - sh ./run-integrationtests.sh
        services: 
          - docker
    - step:
  pull-requests:
    '{feature/*,fix/*}':
      - step: *build
      - step: *unittest
