image: microsoft/dotnet

pipelines:
  default:
    - step:
        name: Build
        caches:
          - dotnetcore
        script:
          - ./build.sh
    - step:
        name: Unit tests
        script:
          - ./run-unittests.sh
  pull-requests:
    '{feature/*,fix/*}':
      - step:
          name: Build
          caches:
            - dotnetcore
          script:
            - ./build.sh
      - step:
          name: Unit tests
          script:
            - ./run-unittests.sh
